version: '3.8'
services:
  server:
    build: .
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
  client:
    build: .
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=production
